apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      initContainers:
        - name: init-copy-html
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /mnt/html &&
              echo {{ .Files.Get "static/index.html" | quote }} > /mnt/html/index.html
          volumeMounts:
            - name: html
              mountPath: /mnt/html
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nginx-html
        - name: nginx-conf
          configMap:
            name: nginx-static
