# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
